OziBazaar.Web/Controllers/AdController.cs
using OziBazaar.Web.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OziBazaar.Web.Controllers
{
    public class AdController : Controller
    {
        private readonly IProductRepository productRepository;
        //
        // GET: /Ad/
        public AdController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;

        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AdList()
        {
            var lst = productRepository.GetAdvertisementsList();
            return View(lst);
        }
        public ActionResult AddAd()
        {
             ViewBag.Categories= new SelectList( productRepository.GetAllCategories(),"Id","Name");
            return View();
        }
	}
}

OziBazaar.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OziBazaar</title>    
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.0.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="row">
                            <div class="span8">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ozi Bazaar", "Index", "Home", null, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Advertisements", "AdList", "Ad")</li>
                    <li>@Html.ActionLink("Wish List", "Index", "WishList")</li>
                </ul>
            </div>
        <div class="span4">

            @Html.Partial("_LoginPartial")

        </div>
                </div>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ozi Bazaar framework</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Content/bootstrap/js")
    @RenderSection("scripts", required: false)

</body>
</html>